# fly.toml app configuration file generated for web-dev on 2023-09-24T17:47:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "web-dev"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

15.6452,
      46.5637